//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcademiaAPI.Models.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estudiante
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public Nullable<System.DateTime> fechanacimiento { get; set; }
        public Nullable<double> promedionotas { get; set; }
        public Nullable<bool> eshombre { get; set; }
        public Nullable<int> id_tipoSangre { get; set; }
        public string direccion { get; set; }
        public string celular { get; set; }
    
        public virtual TipoSangre TipoSangre { get; set; }
    }
}
